services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - "5434:5432"
  redis:
    image: redis:7.4.1
    ports:
      - "6381:6379"
